baseurl = "https://osak.jp"
title = "osak.jp"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "osa_k"

[params]
  author = "Osamu Koga (osa_k)"
  info = "Full Stack Software Engineer"
  description = "Osamu Koga's personal website"
  keywords = "blog,developer,personal"
  #avatarurl = "images/avatar.jpg"
  gravatar = "osak.63@gmail.com"

  #favicon_32 = "/img/favicon-32x32.png"
  #favicon_16 = "/img/favicon-16x16.png"

  #footercontent = "Enter a text here."
  hideFooter = false
  hideCredits = false
  hideCopyright = false
  since = 2019

  enableTwemoji = true

  colorscheme = "auto"
  hidecolorschemetoggle = false

  #customCSS = ["css/custom.css"]
  #customSCSS = ["scss/custom.scss"]
  #customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/osak"
[[params.social]]
  name = "Mastodon (social.mikutter.hachune.net)"
  icon = "fa fa-mastodon fa-2x"
  weight = 2
  url = "https://social.mikutter.hachune.net/osa_k"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/osa_k"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 4
  url = "https://www.linkedin.com/in/osamu-koga-918676a9"


# Menu links
[[menu.main]]
  name = "Blog (en)"
  weight = 1
  url  = "blog/en/"
[[menu.main]]
  name = "Blog (Hatena)"
  weight = 2
  url  = "https://osak.hatenablog.jp/"
[[menu.main]]
  name = "About"
  weight = 3
  url = "about/"